set -g status-bg "#191724"
set -g status-fg "#e0def4"
set -g status-style "fg=#e0def4,bg=#191724"
set -g status-right-style "fg=#908caa,bg=#191724"
set -g window-status-style "fg=#908caa,bg=#191724"
set -g window-status-current-style "fg=#191724,bg=#9ccfd8,bold"
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "
set -g status-right "#[fg=#f6c177]%Y-%m-%d #[fg=#9ccfd8]%H:%M #[default]"
set -g pane-border-style "fg=#403d52"
set -g pane-active-border-style "fg=#9ccfd8"
set -g message-style "fg=#191724,bg=#f6c177,bold"
set -g message-command-style "fg=#191724,bg=#9ccfd8,bold"
set -g mode-style "fg=#191724,bg=#c4a7e7,bold"
set -g clock-mode-colour "#9ccfd8"
