if-shell 'test "$(uname -s)" = Darwin' 'set-environment -g DOTFILES_PROFILE macos-personal' 'set-environment -g DOTFILES_PROFILE linux-personal'

bind -r C new-window "$HOME/.local/bin/tmux-sessionizer" "$HOME/projects/c"
bind -r E new-window "$HOME/.local/bin/tmux-sessionizer" "$HOME/projects/adventofcode"
